name: Publish Package and Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js and npm
      - uses: actions/setup-node@v3
        with:
          node-version: "20.12.x"
          registry-url: "https://registry.npmjs.org"

      # Install dependencies
      - run: yarn

      # Publish the package to npm
      - name: Publish Package
        run: yarn publish --non-interactive --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Create and push a tag based on the version in package.json
      - name: Create and Push Tag
        id: tag_version
        run: |
          git tag "v$(node -p "require('./package.json').version")"
          git push origin "v$(node -p "require('./package.json').version")"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          tag_name: "v${{ git describe --tags }}"
          release_name: "Release v${{ git describe --tags }}"
          body: "Release of version v${{ git describe --tags }}."
          draft: false
          prerelease: false
