name: "Tests"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: "validate(node: ${{ matrix.node }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.19.x, 20.12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn
      # TODO: Have to fix linter
      # - name: Run lint
      #   run: yarn lint
      - name: Run Test
        run: yarn test
